name: infra tf  Automation

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  automate infra deployment :
    runs-on : ubuntu-latest
    env:
      gcp_credential: ${{secrets.GCP_CRED}}
      SERVICE_ACCOUNT: 'naveen-mid-access@inviz-gcp.iam.gserviceaccount.com'
    steps :
      - uses: actions/checkout@v2
      - name: test
        run: |
          sudo snap install google-cloud-cli --classic
          gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=$gcp_credential
          sudo snap install terraform --classic 
          terraform init 
          terraform plan -out=planfile
          terraform apply planfile
