
name: Hell YEah
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  automate_infra_deployment :
    runs-on : ubuntu-latest
    env:
      gcp_credential: ${{secrets.GCP_CRED}}
      SERVICE_ACCOUNT: 'naveen-mid-access@inviz-gcp.iam.gserviceaccount.com'
    steps :
      #- uses: actions/checkout@v2
      - name: test
        run: |
          echo hii
          #terraform init 
          #terraform plan -out=$d
          #terraform apply $d
          #gsutil cp $d  gs://search-tf-test/tf-test
          #terraform destroy --auto-approve
          # rm temp.json
     #
      - if: contains('hII','Z')
        name: testing  
        uses: actions/checkout@v2 
      - name: testing contd 
        run:  |
          chmod +x ./script.sh
          bash ./script.sh

        
