name: infra tf  Automation

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  automate_infra_deployment :
    runs-on : ubuntu-latest
    env:
      gcp_credential: ${{secrets.GCP_CRED}}
      SERVICE_ACCOUNT: 'tf-owner@search-tf-test.iam.gserviceaccount.com'
    steps :
      - uses: actions/checkout@v2
      - name: test
        run: |
          export d=$(date)
          export d=${d// /}
          echo $gcp_credential > temp.json
          sudo snap install google-cloud-cli --classic
          gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=temp.json
          sudo snap install terraform --classic 
          gcloud config set account $SERVICE_ACCOUNT
          export GOOGLE_APPLICATION_CREDENTIALS=temp.json
          terraform init 
          terraform plan -out=$d
          terraform apply $d
          gsutil cp $d  gs://search-tf-test/tf-test
          terraform destroy --auto-approve
          rm temp.json
